Repository money-fragments/money-fragments-client, pull requests merged in 2023-01, with the labels that each got.

#17 docs: create pull request template
  .github/pull_request_template.md
Labels: documentation

#19 chore: init chore
  package-lock.json
  package.json
  src/App.tsx
  yarn.lock
Labels: enhancement

#20 Docs/init
  .prettierrc.yml
  src/components/auth/index.ts
  src/components/common/index.ts
  src/components/layouts/index.ts
  src/components/main/index.ts
  src/components/my-page/index.ts
  src/hooks/index.ts
  src/pages/index.ts
  src/shared/Router.tsx
  src/types.d.ts
  src/utils/index.ts
Labels: documentation

#21 feat: create Router
  src/App.tsx
  src/components/landing/Landing.tsx
  src/components/landing/index.ts
  src/shared/Router.tsx
Labels: enhancement

#22 feat: apply theme provider
  src/App.tsx
  src/components/common/TextComponents.tsx
  src/components/common/index.ts
  src/styles/GlobalStyle.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: enhancement

#23 feat: create My Page UI
  src/components/my-page/DetailExpenseItem.tsx
  src/components/my-page/DtailMonthlyExpense.tsx
  src/components/my-page/ExpenseReport.tsx
  src/components/my-page/MonthlyExpense.tsx
  src/components/my-page/MonthlyExpenseBar.tsx
  src/components/my-page/index.ts
  src/pages/MyPage.tsx
  src/pages/index.ts
Labels: enhancement

#24 fix : black과 white부분 theme에 추가하여 배경 색상 사용 시 자동완성으로 사용 가능.
  src/components/landing/Landing.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  yarn.lock
Labels: enhancement

#26 UI/UI auth login
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/components/auth/index.ts
  src/components/landing/Landing.tsx
  src/shared/Router.tsx
  src/styles/GlobalStyle.tsx
Labels: enhancement

#27 UI/UI auth sign up
  src/components/auth/SignUp.tsx
  src/firebase.tsx
  src/index.tsx
  tsconfig.json
Labels: enhancement

#28 Feat/button component
  src/components/common/CustomButton.tsx
  src/components/common/CustomInput.tsx
  yarn.lock
Labels: enhancement

#37 Feat/landing page
  src/components/assets/landingpage.png
  src/components/assets/logo.png
  src/components/assets/logo2.png
  src/components/landing/Landing.tsx
  src/components/layouts/Layout.tsx
  src/components/layouts/NavigationBar.tsx
  src/components/layouts/index.ts
  src/shared/Router.tsx
  yarn.lock
Labels: enhancement

#38 ui/Main-Detail-ui 생성되었습니다
  src/components/common/CustomButton.tsx
  src/components/common/CustomInput.tsx
  src/components/main/Main.tsx
  src/components/main/MainDetailUi.tsx
  src/components/main/index.ts
  src/shared/Router.tsx
Labels: enhancement

#36 feat : auth-logic 진행합니다.( 일부 UI는 진행 전인 상태로 코드 리뷰를 먼저 후 진행하고자 해서 진행합니다.)
  package-lock.json
  src/components/auth/AuthForgot.tsx
  src/components/auth/AuthSocial.tsx
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/components/main/Main.tsx
  src/shared/AuthRoute.tsx
  src/shared/Router.tsx
  yarn.lock
Labels: enhancement

#39 feat : create Reusable CustomModal, CustomAlert
  package-lock.json
  package.json
  src/components/common/CustomButton.tsx
  src/components/common/CustomInput.tsx
  src/components/common/CustomModal.tsx
  src/components/landing/Landing.tsx
  src/utils/index.ts
  yarn.lock
Labels: enhancement

#41 Feat/dev hot fix
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/components/landing/Landing.tsx
  src/components/layouts/Layout.tsx
  src/components/layouts/NavigationBar.tsx
  src/components/main/Main.tsx
  src/components/main/MainDetailUi.tsx
  src/shared/Router.tsx
  yarn.lock
Labels: enhancement

#42 Feat/monthly expense
  src/components/my-page/ExpenseReport.tsx
  src/components/my-page/MonthlyExpense.tsx
  src/hooks/useUserExpenses.ts
  src/hooks/useUserExpensesYears.ts
  src/shared/Router.tsx
  src/types.d.ts
  src/utils/api.ts
Labels: enhancement

#43 refactor: refactor custom alert, confirm
  src/utils/alerts.ts
  src/utils/index.ts
Labels: enhancement

#44 feat: detail monthly expenses 기능 추가
  package-lock.json
  src/components/my-page/DetailExpenseItem.tsx
  src/components/my-page/DetailMonthlyExpense.tsx
  src/components/my-page/DtailMonthlyExpense.tsx
  src/components/my-page/ExpenseReport.tsx
  src/components/my-page/MonthlyExpense.tsx
  src/components/my-page/index.ts
  src/hooks/useUserExpenses.ts
  src/hooks/useUserExpensesYears.ts
  src/pages/MyPage.tsx
  yarn.lock
Labels: enhancement

#46 refactor: ui/ux
  src/components/auth/AuthSocial.tsx
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/components/common/CustomButton.tsx
  src/components/landing/Landing.tsx
  src/components/layouts/NavigationBar.tsx
  src/shared/AuthRoute.tsx
  src/styles/GlobalStyle.tsx
  src/utils/alerts.ts
Labels: enhancement

#48 feat: create post expense
  src/components/landing/Landing.tsx
  src/components/main/Maps.tsx
  src/components/main/PopupMemo.tsx
  src/components/my-page/DetailMonthlyExpense.tsx
  src/components/my-page/ExpenseReport.tsx
  src/components/my-page/MonthlyExpense.tsx
  src/pages/MyPage.tsx
  src/types.d.ts
  src/utils/api.ts
  yarn.lock
Labels: enhancement

#51 feat : 유효성검사 진행 됨
  package-lock.json
  package.json
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
Labels: enhancement

#57 hotfix
  src/components/calendar/Calendar.tsx
  src/components/layouts/NavigationBar.tsx
  src/components/main/MainDetailUi.tsx
  src/components/main/Maps.tsx
  src/components/main/PlaceItem.tsx
  src/components/main/PopupMemo.tsx
  src/components/main/SearchPlace.tsx
  src/components/main/index.ts
  src/pages/Main.tsx
  src/shared/Router.tsx
Labels: bug, enhancement
